In [3]:
import pandas as pd

In [5]:
df = pd.read_csv('./offsets3.csv')
df

,0.000000 0.000000,0.000000 0.000000.1,0.000000 0.000000.2,0.000000 0.000000.3,0.000000 0.000000.4,0.000000 0.000000.5,0.000000 0.000000.6,0.000000 0.000000.7,0.000000 0.000000.8,0.000000 0.000000.9,...,0.000000 0.000000.1650,0.000000 0.000000.1651,0.000000 0.000000.1652,0.000000 0.000000.1653,0.000000 0.000000.1654,0.000000 0.000000.1655,0.000000 0.000000.1656,0.000000 0.000000.1657,0.000000 0.000000.1658,0.000000 0.000000.1659
0,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,...,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000
1,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,...,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000
2,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,...,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000
3,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,...,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000
4,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,...,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8634,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,-40303.276479 165139.440491,0.000000 0.000000,0.000000 0.000000,-38637.154645 164641.775684,...,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,-86234.683708 -104641.552075,0.000000 0.000000
8635,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,-40303.276479 165139.440491,0.000000 0.000000,0.000000 0.000000,-38637.160516 164640.665111,...,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,-86234.683708 -104641.552075,0.000000 0.000000
8636,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,-40303.276479 165139.440491,0.000000 0.000000,0.000000 0.000000,-38637.160516 164640.665111,...,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,-86234.683708 -104641.552075,0.000000 0.000000
8637,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,-40303.276479 165139.440491,0.000000 0.000000,0.000000 0.000000,-38637.154645 164641.775684,...,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,-86234.683708 -104641.552075,0.000000 0.000000
8638,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,-40303.276479 165139.440491,0.000000 0.000000,0.000000 0.000000,-38637.154645 164641.775684,...,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,0.000000 0.000000,-86234.683708 -104641.552075,0.000000 0.000000

In [14]:
a = [1,2,3,4]
for i in a:
    print(i, end='')
print('')
print('-')

1234
-

In [17]:
df[' ']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
8635   NaN
8636   NaN
8637   NaN
8638   NaN
8639   NaN
Name:  , Length: 8640, dtype: float64

In [18]:
df = df.drop(columns=[' '])

In [33]:
df['20000003']

KeyError: '20000003'

In [1]:
24*60*60

86400

In [9]:
df.shape

(8639, 1660)